name: Build and Release

on:
  push:
    branches:
      - develop

jobs:
  build:
    permissions:
      contents: write

    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Node
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Install frontend dependencies
        run: pnpm install

      # Rust cache
      - name: Cache Rust
        uses: swatinem/rust-cache@v2
        with:
          workspaces: src-tauri

      # Build + Release
      - name: Build Tauri App
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: v__VERSION__
          releaseName: "Tauri App v__VERSION__"
          releaseDraft: false
          prerelease: false