name: Build Tauri App

on:
  push:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-pc-windows-msvc
          default: true

      - name: Install Tauri CLI
        run: npm install -g @tauri-apps/cli

      - name: Install dependencies
        run: npm install

      - name: Build Tauri App
        run: npm run tauri build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: tauri-build
          path: src-tauri/target/release/bundle/msi/
